global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'file-storage-service'
    metrics_path: '/file-storage-service/actuator/prometheus'
    static_configs:
      - targets: ['filestorageservice-app:8080']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'file-storage-service'
